# Generated by Django 4.0.4 on 2022-05-07 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('Techno', 'Techno'), ('Hollywood', 'Hollywood'), ('Folk', 'Folk'), ('Bollywood', 'Bollywood'), ('Rock', 'Rock'), ('Pop Music', 'Pop Music'), ('Classical', 'Classical'), ('Hip Hop Music', 'Hip Hop Music')], max_length=200)),
                ('rating', models.FloatField(default=0)),
                ('AlbumImage', models.ImageField(default=None, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('Punjabi', 'Punjabi'), ('English', 'English'), ('Kumaoni', 'Kumaoni'), ('Hindi', 'Hindi')], max_length=200)),
                ('songImg', models.FileField(upload_to='')),
                ('singer', models.CharField(max_length=200)),
                ('songFile', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistName', models.CharField(max_length=200)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isFav', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
