# Generated by Django 4.0.4 on 2022-05-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Pop Music', 'Pop Music'), ('Metal', 'Metal'), ('Hip Hop and Rap', 'Hip Hop and Rap'), ('Bollywood', 'Bollywood'), ('K-POP', 'K-POP'), ('Rock', 'Rock'), ('Techno', 'Techno'), ('Hollywood', 'Hollywood'), ('Classical', 'Classical'), ('Folk', 'Folk')], max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Kumaoni', 'Kumaoni'), ('Punjabi', 'Punjabi'), ('korean', 'korean')], max_length=200),
        ),
    ]
