# Generated by Django 4.0.4 on 2022-05-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_alter_album_genre_alter_song_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Classical', 'Classical'), ('Folk', 'Folk'), ('Bollywood', 'Bollywood'), ('Techno', 'Techno'), ('Hip Hop and Rap', 'Hip Hop and Rap'), ('K-POP', 'K-POP'), ('Hollywood', 'Hollywood'), ('Pop Music', 'Pop Music'), ('Rock', 'Rock')], max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Punjabi', 'Punjabi'), ('Kumaoni', 'Kumaoni'), ('korean', 'korean')], max_length=200),
        ),
    ]
