# Generated by Django 4.0.4 on 2023-02-19 17:41

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_alter_album_genre_alter_song_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelWithRawFileAndImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raw_file', models.ImageField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='raw/')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Techno', 'Techno'), ('Bollywood', 'Bollywood'), ('Classical', 'Classical'), ('Folk', 'Folk'), ('Rock', 'Rock'), ('Hip Hop and Rap', 'Hip Hop and Rap'), ('Hollywood', 'Hollywood'), ('Pop Music', 'Pop Music'), ('K-POP', 'K-POP'), ('Metal', 'Metal')], max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Punjabi', 'Punjabi'), ('English', 'English'), ('Hindi', 'Hindi'), ('Kumaoni', 'Kumaoni'), ('korean', 'korean')], max_length=200),
        ),
    ]
