# Generated by Django 4.0.4 on 2023-04-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_testmodelwithrawfileandimage_alter_album_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('K-POP', 'K-POP'), ('Hollywood', 'Hollywood'), ('Techno', 'Techno'), ('Hip Hop and Rap', 'Hip Hop and Rap'), ('Metal', 'Metal'), ('Rock', 'Rock'), ('Pop Music', 'Pop Music'), ('Bollywood', 'Bollywood'), ('Classical', 'Classical'), ('Folk', 'Folk')], max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Kumaoni', 'Kumaoni'), ('Hindi', 'Hindi'), ('korean', 'korean'), ('Punjabi', 'Punjabi'), ('English', 'English')], max_length=200),
        ),
    ]
