# Generated by Django 4.0.4 on 2023-04-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_alter_album_genre_alter_song_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Techno', 'Techno'), ('K-POP', 'K-POP'), ('Pop Music', 'Pop Music'), ('Classical', 'Classical'), ('Hollywood', 'Hollywood'), ('Metal', 'Metal'), ('Folk', 'Folk'), ('Hip Hop and Rap', 'Hip Hop and Rap'), ('Bollywood', 'Bollywood'), ('Rock', 'Rock')], max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('korean', 'korean'), ('Hindi', 'Hindi'), ('Kumaoni', 'Kumaoni'), ('Punjabi', 'Punjabi')], max_length=200),
        ),
    ]
