# Generated by Django 4.0.4 on 2023-04-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_alter_album_genre_alter_song_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Bollywood', 'Bollywood'), ('K-POP', 'K-POP'), ('Pop Music', 'Pop Music'), ('Classical', 'Classical'), ('Hollywood', 'Hollywood'), ('Techno', 'Techno'), ('Folk', 'Folk'), ('Rock', 'Rock'), ('Metal', 'Metal'), ('Hip Hop and Rap', 'Hip Hop and Rap')], max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Punjabi', 'Punjabi'), ('English', 'English'), ('Kumaoni', 'Kumaoni'), ('Hindi', 'Hindi'), ('korean', 'korean')], max_length=200),
        ),
    ]
