# Generated by Django 4.0.4 on 2023-04-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0007_alter_album_genre_alter_song_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Hip Hop and Rap', 'Hip Hop and Rap'), ('Folk', 'Folk'), ('Rock', 'Rock'), ('Techno', 'Techno'), ('Metal', 'Metal'), ('Pop Music', 'Pop Music'), ('Classical', 'Classical'), ('Bollywood', 'Bollywood'), ('K-POP', 'K-POP'), ('Hollywood', 'Hollywood')], max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Kumaoni', 'Kumaoni'), ('Punjabi', 'Punjabi'), ('korean', 'korean'), ('English', 'English'), ('Hindi', 'Hindi')], max_length=200),
        ),
    ]
