# Generated by Django 4.0.4 on 2023-04-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0008_alter_album_genre_alter_song_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Hollywood', 'Hollywood'), ('Pop Music', 'Pop Music'), ('Bollywood', 'Bollywood'), ('Metal', 'Metal'), ('Hip Hop and Rap', 'Hip Hop and Rap'), ('Techno', 'Techno'), ('K-POP', 'K-POP'), ('Folk', 'Folk'), ('Rock', 'Rock'), ('Classical', 'Classical')], max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Punjabi', 'Punjabi'), ('Hindi', 'Hindi'), ('korean', 'korean'), ('Kumaoni', 'Kumaoni'), ('English', 'English')], max_length=200),
        ),
    ]
