# Generated by Django 4.0.4 on 2023-04-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0009_alter_album_genre_alter_song_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Techno', 'Techno'), ('Pop Music', 'Pop Music'), ('Classical', 'Classical'), ('Hollywood', 'Hollywood'), ('K-POP', 'K-POP'), ('Folk', 'Folk'), ('Hip Hop and Rap', 'Hip Hop and Rap'), ('Rock', 'Rock'), ('Bollywood', 'Bollywood')], max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Punjabi', 'Punjabi'), ('korean', 'korean'), ('Hindi', 'Hindi'), ('English', 'English'), ('Kumaoni', 'Kumaoni')], max_length=200),
        ),
    ]
