# Generated by Django 5.0.1 on 2024-01-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0012_alter_album_genre_alter_song_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Classical', 'Classical'), ('Folk', 'Folk'), ('Hip Hop and Rap', 'Hip Hop and Rap'), ('Bollywood', 'Bollywood'), ('Techno', 'Techno'), ('Hollywood', 'Hollywood'), ('K-POP', 'K-POP'), ('Rock', 'Rock'), ('Pop Music', 'Pop Music'), ('Metal', 'Metal')], max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('korean', 'korean'), ('English', 'English'), ('Kumaoni', 'Kumaoni'), ('Hindi', 'Hindi'), ('Punjabi', 'Punjabi')], max_length=200),
        ),
    ]
